language: java
jdk:
  - openjdk8

# Git Push할 Branch
branches:
  only:
    - master # 여기 바꿔도 됨!

# gradlew 권한 추가
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - wpals113@snu.ac.kr # 여기 바꿔도 됨!

before_deploy:
  - zip -r springboot-webservice-study * # 본인의 프로젝트명
  - mkdir -p deploy
  - mv springboot-webservice-study.zip deploy/springboot-webservice-study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo Settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo Settings에 설정된 값
    bucket: jaemin-springboot-buildset # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true